INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('God''s Plan', 'Drake', 'Rap', 1, 198973.0, 'Gods_Plan.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('SAD!', 'XXXTENTACION', 'Rap', 2, 166606.0, 'SAD.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('rockstar (feat. 21 Savage)', 'Post Malone', 'Indefinido', 3, 218147.0, 'rockstar_feat_21_Savage.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Psycho (feat. Ty Dolla $ign)', 'Post Malone', 'Rap', 4, 221440.0, 'Psycho_feat_Ty_Dolla_ign.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('In My Feelings', 'Drake', 'Pop', 5, 217925.0, 'In_My_Feelings.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Better Now', 'Post Malone', 'Indefinido', 6, 231267.0, 'Better_Now.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('I Like It', 'Cardi B', 'Pop', 7, 253390.0, 'I_Like_It.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('One Kiss (with Dua Lipa)', 'Calvin Harris', 'Pop', 8, 214847.0, 'One_Kiss_with_Dua_Lipa.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('IDGAF', 'Dua Lipa', 'Rock', 9, 217947.0, 'IDGAF.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('FRIENDS', 'Marshmello', 'Pop', 10, 202621.0, 'FRIENDS.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Havana', 'Camila Cabello', 'Rock', 11, 217307.0, 'Havana.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Lucid Dreams', 'Juice WRLD', 'Rap', 12, 239836.0, 'Lucid_Dreams.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Nice For What', 'Drake', 'Pop', 13, 210747.0, 'Nice_For_What.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Girls Like You (feat. Cardi B)', 'Maroon 5', 'Acoustic', 14, 235545.0, 'Girls_Like_You_feat_Cardi_B.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('The Middle', 'Zedd', 'Pop', 15, 184732.0, 'The_Middle.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('All The Stars (with SZA)', 'Kendrick Lamar', 'Pop', 16, 232187.0, 'All_The_Stars_with_SZA.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('no tears left to cry', 'Ariana Grande', 'Pop', 17, 205920.0, 'no_tears_left_to_cry.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('X', 'Nicky Jam', 'Pop', 18, 173628.0, 'X.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Moonlight', 'XXXTENTACION', 'Acoustic', 19, 135090.0, 'Moonlight.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Look Alive (feat. Drake)', 'BlocBoy JB', 'Rap', 20, 181263.0, 'Look_Alive_feat_Drake.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('These Days (feat. Jess Glynne, Macklemore & Dan Caplen)', 'Rudimental', 'Pop', 21, 210773.0, 'These_Days_feat_Jess_Glynne_Macklemore__Dan_Caplen.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Te Bot? - Remix', 'Nio Garcia', 'Pop', 22, 417920.0, 'Te_Bot__Remix.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Mine', 'Bazzi', 'Pop', 23, 131064.0, 'Mine.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Youngblood', '5 Seconds of Summer', 'Rap', 24, 203418.0, 'Youngblood.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('New Rules', 'Dua Lipa', 'Pop', 25, 209320.0, 'New_Rules.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Shape of You', 'Ed Sheeran', 'Pop', 26, 233713.0, 'Shape_of_You.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Love Lies (with Normani)', 'Khalid', 'Pop', 27, 201707.0, 'Love_Lies_with_Normani.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Meant to Be (feat. Florida Georgia Line)', 'Bebe Rexha', 'Pop', 28, 164205.0, 'Meant_to_Be_feat_Florida_Georgia_Line.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Jocelyn Flores', 'XXXTENTACION', 'Acoustic', 29, 119133.0, 'Jocelyn_Flores.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Perfect', 'Ed Sheeran', 'Indefinido', 30, 263400.0, 'Perfect.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Taste (feat. Offset)', 'Tyga', 'Rap', 31, 232959.0, 'Taste_feat_Offset.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Solo (feat. Demi Lovato)', 'Clean Bandit', 'Pop', 32, 222653.0, 'Solo_feat_Demi_Lovato.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('I Fall Apart', 'Post Malone', 'Blues', 33, 223347.0, 'I_Fall_Apart.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Nevermind', 'Dennis Lloyd', 'Rap', 34, 156600.0, 'Nevermind.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('?chame La Culpa', 'Luis Fonsi', 'Pop', 35, 173720.0, 'chame_La_Culpa.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Eastside (with Halsey & Khalid)', 'benny blanco', 'Rap', 36, 173800.0, 'Eastside_with_Halsey__Khalid.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Never Be the Same', 'Camila Cabello', 'Rock', 37, 226973.0, 'Never_Be_the_Same.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Wolves', 'Selena Gomez', 'Pop', 38, 197993.0, 'Wolves.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('changes', 'XXXTENTACION', 'Acoustic', 39, 121887.0, 'changes.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('In My Mind', 'Dynoro', 'Rap', 40, 184560.0, 'In_My_Mind.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('River (feat. Ed Sheeran)', 'Eminem', 'Pop', 41, 221013.0, 'River_feat_Ed_Sheeran.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Dura', 'Daddy Yankee', 'Pop', 42, 200480.0, 'Dura.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('SICKO MODE', 'Travis Scott', 'Pop', 43, 312820.0, 'SICKO_MODE.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Thunder', 'Imagine Dragons', 'Rock', 44, 187147.0, 'Thunder.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Me Niego', 'Reik', 'Pop', 45, 221653.0, 'Me_Niego.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Jackie Chan', 'Ti?sto', 'Pop', 46, 215760.0, 'Jackie_Chan.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Finesse (Remix) [feat. Cardi B]', 'Bruno Mars', 'Pop', 47, 217289.0, 'Finesse_Remix_feat_Cardi_B.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Back To You - From 13 Reasons Why ? Season 2 Soundtrack', 'Selena Gomez', 'Pop', 48, 207905.0, 'Back_To_You__From_13_Reasons_Why__Season_2_Soundtrack.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Let You Down', 'NF', 'Pop', 49, 212120.0, 'Let_You_Down.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Call Out My Name', 'The Weeknd', 'Indefinido', 50, 228373.0, 'Call_Out_My_Name.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Ric Flair Drip (& Metro Boomin)', 'Offset', 'Rap', 51, 172800.0, 'Ric_Flair_Drip__Metro_Boomin.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Happier', 'Marshmello', 'Pop', 52, 214290.0, 'Happier.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Too Good At Goodbyes', 'Sam Smith', 'Acoustic', 53, 201000.0, 'Too_Good_At_Goodbyes.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Freaky Friday (feat. Chris Brown)', 'Lil Dicky', 'Rap', 54, 216632.0, 'Freaky_Friday_feat_Chris_Brown.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Believer', 'Imagine Dragons', 'Pop', 55, 204347.0, 'Believer.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('FEFE (feat. Nicki Minaj & Murda Beatz)', '6ix9ine', 'Indefinido', 56, 179405.0, 'FEFE_feat_Nicki_Minaj__Murda_Beatz.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Rise', 'Jonas Blue', 'Pop', 57, 194408.0, 'Rise.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Body (feat. brando)', 'Loud Luxury', 'Pop', 58, 163216.0, 'Body_feat_brando.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('XO TOUR Llif3', 'Lil Uzi Vert', 'Pop', 59, 182707.0, 'XO_TOUR_Llif3.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Sin Pijama', 'Becky G', 'Pop', 60, 188560.0, 'Sin_Pijama.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('2002', 'Anne-Marie', 'Pop', 61, 186987.0, '2002.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Nonstop', 'Drake', 'Rap', 62, 238614.0, 'Nonstop.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Fuck Love (feat. Trippie Redd)', 'XXXTENTACION', 'Indefinido', 63, 146520.0, 'Fuck_Love_feat_Trippie_Redd.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('In My Blood', 'Shawn Mendes', 'Pop', 64, 211360.0, 'In_My_Blood.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Silence', 'Marshmello', 'Rock', 65, 180823.0, 'Silence.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('God is a woman', 'Ariana Grande', 'Indefinido', 66, 197547.0, 'God_is_a_woman.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('D?jala que vuelva (feat. Manuel Turizo)', 'Piso 21', 'Pop', 67, 220117.0, 'Djala_que_vuelva_feat_Manuel_Turizo.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Flames', 'David Guetta', 'Pop', 68, 194680.0, 'Flames.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('What Lovers Do', 'Maroon 5', 'Dance', 69, 199849.0, 'What_Lovers_Do.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Taki Taki (with Selena Gomez, Ozuna & Cardi B)', 'DJ Snake', 'Pop', 70, 212500.0, 'Taki_Taki_with_Selena_Gomez_Ozuna__Cardi_B.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Let Me Go (with Alesso, Florida Georgia Line & watt)', 'Hailee Steinfeld', 'Pop', 71, 174800.0, 'Let_Me_Go_with_Alesso_Florida_Georgia_Line__watt.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Feel It Still', 'Portugal. The Man', 'Blues', 72, 163253.0, 'Feel_It_Still.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Pray For Me (with Kendrick Lamar)', 'The Weeknd', 'Rock', 73, 211440.0, 'Pray_For_Me_with_Kendrick_Lamar.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Walk It Talk It', 'Migos', 'Pop', 74, 276147.0, 'Walk_It_Talk_It.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Him & I (with Halsey)', 'G-Eazy', 'Rock', 75, 268867.0, 'Him__I_with_Halsey.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Candy Paint', 'Post Malone', 'Pop', 76, 227533.0, 'Candy_Paint.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Congratulations', 'Post Malone', 'Pop', 77, 220293.0, 'Congratulations.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('1, 2, 3 (feat. Jason Derulo & De La Ghetto)', 'Sofia Reyes', 'Pop', 78, 201526.0, '1_2_3_feat_Jason_Derulo__De_La_Ghetto.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Criminal', 'Natti Natasha', 'Dance', 79, 232550.0, 'Criminal.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Plug Walk', 'Rich The Kid', 'Rap', 80, 175230.0, 'Plug_Walk.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('lovely (with Khalid)', 'Billie Eilish', 'Acoustic', 81, 200186.0, 'lovely_with_Khalid.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Stir Fry', 'Migos', 'Pop', 82, 190288.0, 'Stir_Fry.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('HUMBLE.', 'Kendrick Lamar', 'Pop', 83, 177000.0, 'HUMBLE.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Vaina Loca', 'Ozuna', 'Pop', 84, 176133.0, 'Vaina_Loca.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Perfect Duet (Ed Sheeran & Beyonc?)', 'Ed Sheeran', 'Acoustic', 85, 259550.0, 'Perfect_Duet_Ed_Sheeran__Beyonc.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Coraz?n (feat. Nego do Borel)', 'Maluma', 'Pop', 86, 184720.0, 'Corazn_feat_Nego_do_Borel.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Young Dumb & Broke', 'Khalid', 'Indefinido', 87, 202547.0, 'Young_Dumb__Broke.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('S?guelo Bailando', 'Ozuna', 'Pop', 88, 226800.0, 'Sguelo_Bailando.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Downtown', 'Anitta', 'Pop', 89, 193456.0, 'Downtown.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Bella', 'Wolfine', 'Dance', 90, 197120.0, 'Bella.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Promises (with Sam Smith)', 'Calvin Harris', 'Pop', 91, 213309.0, 'Promises_with_Sam_Smith.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Yes Indeed', 'Lil Baby', 'Dance', 92, 142273.0, 'Yes_Indeed.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('I Like Me Better', 'Lauv', 'Rap', 93, 197437.0, 'I_Like_Me_Better.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('This Is Me', 'Keala Settle', 'Rap', 94, 234707.0, 'This_Is_Me.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Everybody Dies In Their Nightmares', 'XXXTENTACION', 'Rap', 95, 95467.0, 'Everybody_Dies_In_Their_Nightmares.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Rewrite The Stars', 'Zac Efron', 'Indefinido', 96, 217440.0, 'Rewrite_The_Stars.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('I Miss You (feat. Julia Michaels)', 'Clean Bandit', 'Pop', 97, 205748.0, 'I_Miss_You_feat_Julia_Michaels.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('No Brainer', 'DJ Khaled', 'Pop', 98, 260000.0, 'No_Brainer.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Dusk Till Dawn - Radio Edit', 'ZAYN', 'Indefinido', 99, 239000.0, 'Dusk_Till_Dawn__Radio_Edit.jpg');
INSERT INTO song (title, artist, genre, popularity, duration_ms, cover_image) VALUES ('Be Alright', 'Dean Lewis', 'Acoustic', 100, 196373.0, 'Be_Alright.jpg');
